alexrogna/config/routes.rb
Rails.application.routes.draw do
  resources :personal_skills
  resources :contact_forms
  resources :educations
  resources :teches
  resources :works
  resources :language_skills
  resources :skills do
    resources :books
    resources :hacker_ranks
    resources :free_code_camps
    resources :linkedins
  end
  resources :books
  resources :hacker_ranks
  resources :free_code_camps
  resources :linkedins
  resources :tags
  resources :projects
  resources :social_icons
  namespace :settings do
    resource :user, only: [:show, :update] do
      member do
        post :notify_friend
      end
    end
  end
  devise_for :users, controllers: { sessions: "sessions" }
  get :cv, to: "cv#pdf"
  root "home#index"
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

alexrogna/app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :skills
  has_one_attached :cover
end

alexrogna/app/models/contact_form.rb
class ContactForm < ApplicationRecord
  validates :name, :email, :message, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

alexrogna/app/models/education.rb
class Education < ApplicationRecord
  has_and_belongs_to_many :teches
  accepts_nested_attributes_for :teches, reject_if: :all_blank, allow_destroy: true
  has_rich_text :courses
end

alexrogna/app/models/email_a_friend.rb
class EmailAFriend
  include ActiveModel::Model
  
  attr_accessor :name, :email, :yemail

  validates :name, :email, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  
end

alexrogna/app/models/free_code_camp.rb
class FreeCodeCamp < ApplicationRecord
  has_and_belongs_to_many :skills
  has_one_attached :certificate
end

alexrogna/app/models/hacker_rank.rb
class HackerRank < ApplicationRecord
  has_and_belongs_to_many :skills
end

alexrogna/app/models/linkedin.rb
class Linkedin < ApplicationRecord
  has_and_belongs_to_many :skills
  has_one_attached :badge
end

alexrogna/app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true
  has_one_attached :cover_image
  has_one_attached :logo
  has_one_attached :main_tech
  has_one_attached :project_logo
  has_rich_text :description
end

alexrogna/app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :books
  has_and_belongs_to_many :hacker_ranks
  has_and_belongs_to_many :free_code_camps
  has_and_belongs_to_many :linkedins
  has_and_belongs_to_many :teches
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :books, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :hacker_ranks, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :free_code_camps, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :linkedins, reject_if: :all_blank, allow_destroy: true
  has_one_attached :logo
end

alexrogna/app/models/social_icon.rb
class SocialIcon < ApplicationRecord
end

alexrogna/app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :skills
  validates :name, uniqueness: true
end

alexrogna/app/models/tech.rb
class Tech < ApplicationRecord
  has_and_belongs_to_many :works
  has_and_belongs_to_many :educations
  has_and_belongs_to_many :skills
  validates :name, uniqueness: true
  has_one_attached :logo
end

alexrogna/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_one_attached :cover_image
  has_one_attached :profile_image
  has_one_attached :cv
  has_rich_text :long_description_wysiwyg
  has_rich_text :extra_description_for_pdf
end

alexrogna/app/models/work.rb
class Work < ApplicationRecord
  has_and_belongs_to_many :teches
  accepts_nested_attributes_for :teches, reject_if: :all_blank, allow_destroy: true
  has_rich_text :key_responsibilities
end

alexrogna/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /projects or /projects.json
  def index
    @tags = Tag.all.order("name ASC")
    tag = params[:tag]
    if !tag.nil?
      @projects = Project.joins(:tags).where(tags: {id: tag})
    else
      @projects = Project.all
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @projects = Project.all.order("order_id DESC")
  end

  # GET /projects/1/edit
  def edit
    @projects = Project.all.order("order_id DESC")
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path + "#portfolio", notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_path + "#portfolio", notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_path + "#portfolio", notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :url, :github_url, :docker_url, :cover_image, :logo, :main_tech, :project_logo, :hidden, :order_id, tag_ids: [], tags_attributes:[:name, :_destroy])
    end
end

alexrogna/app/helpers/books_helper.rb
module BooksHelper
end

alexrogna/app/helpers/cv_helper.rb
module CvHelper
  def links(link)
    link.gsub("https://", "")
  end
end

alexrogna/app/helpers/home_helper.rb
module HomeHelper
  def procent(skill)
    # total projects, work places and education places
    total = @projects.count + @works.count + @educations.count
    #start from 0
    found_in_projects=found_in_work_places=found_in_education_places=0 
    # how many times is found the skill by name tag in projects
    @projects.each do |project| 
      found_in_projects += project.tags.count{ |tag| tag.name.downcase==skill.name.downcase||(tag.skills.count{|s| s.name.downcase==skill.name.downcase}>0) } 
    end 
    #how many times is found the skill by name tech in work places
    @works.each do |work| 
      found_in_work_places += work.teches.count{ |tech| tech.name.downcase==skill.name.downcase||(tech.skills.count{|s| s.name.downcase==skill.name.downcase}>0) }  
    end 
    #how many times is found the skill by name tech in education places
    @educations.each do |education| 
      found_in_education_places += education.teches.count{ |tech| tech.name.downcase==skill.name.downcase||(tech.skills.count{|s| s.name.downcase==skill.name.downcase}>0) } 
    end 
    # how many times is found the skill in projects, work places and half of the education places, books, linkedin badges, hacker rank certificate and badges, free code camp certificate (this is count as half because is more important to use the skill in real projects/work than to read about it) 
    found_skill = found_in_projects + found_in_work_places + (found_in_education_places + skill.books.count + skill.linkedins.count + skill.hacker_ranks.count + skill.free_code_camps.count)/2
    # final calculation: how many time is found the skill from total 
    (found_skill * 100 / total).to_i
  end 
end

alexrogna/app/helpers/projects_helper.rb
module ProjectsHelper
end

alexrogna/app/helpers/skills_helper.rb
module SkillsHelper
end

alexrogna/app/helpers/tags_helper.rb
module TagsHelper
end

alexrogna/app/helpers/teches_helper.rb
module TechesHelper
end

alexrogna/app/helpers/works_helper.rb
module WorksHelper
end

alexrogna/app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "h-full-width" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "h-full-width" %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, class: "h-full-width" %>
  </div>

  <div class="field">
    <%= form.label :github_url %>
    <%= form.text_field :github_url, class: "h-full-width" %>
  </div>

  <div class="field">
    <%= form.label :docker_url %>
    <%= form.text_field :docker_url, class: "h-full-width" %>
  </div>
  <h3>Add Tags</h3>
  <%= form.collection_check_boxes(:tag_ids, Tag.all.order("name ASC"), :id, :name) do |b| %>
    <% b.label {b.check_box + b.text } %>
  <% end %>
  <div class="links">
      <%= link_to_add_association "Add Tag", form, :tags %>
  </div>
  <%= link_to "View tags", tags_path %>
  <hr>
  <%= form.label :cover_image %>
  <% if project.cover_image.attached? %>
      <%= image_tag project.cover_image.variant(resize_to_limit: local_assigns.fetch(:cover_image_options, [400, 400])) %>
  <% end %>
  <%= form.file_field :cover_image %>
  <hr>
  <%= form.label :logo %>
  <% if project.logo.attached? %>
      <%= image_tag project.logo.variant(resize_to_limit: local_assigns.fetch(:logo_options, [200, 200])) %>
  <% end %>
  <%= form.file_field :logo %>
  <hr>
  <%= form.label :main_tech %>
  <% if project.main_tech.attached? %>
      <%= image_tag project.main_tech.variant(resize_to_limit: local_assigns.fetch(:main_tech_options, [100, 100])) %>
  <% end %>
  <%= form.file_field :main_tech %>
  <hr>
  <%= form.label :project_logo %>
  <% if project.project_logo.attached? %>
      <%= image_tag project.project_logo.variant(resize_to_limit: local_assigns.fetch(:project_logo_options, [200, 200])) %>
  <% end %>
  <%= form.file_field :project_logo %>
  <div class="field">
    <%= form.label :hidden %>
    <%= form.check_box :hidden %>
  </div>
  <div class="field">
    <%= form.label :order_id %>
    <%= form.number_field :order_id %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn--submit h-full-width", disabled: !is_admin(current_user) %>
  </div>
<% end %>

alexrogna/app/views/projects/_index.html.erb
<header class="row">
    <div class="column large-12">
        <h3 class="section-header-allcaps">Portfolio</h3>
    </div>
</header>

<div class="row collapse block-large-1-4 block-medium-1-3 block-tab-1-2 projects-list">
    <% projects.each do |project| %>
    <div class="column item">
        <div class="project-item" style="--content: '<%= project.name %>'">
            <%= link_to "#modal-#{project.order_id}", class:"thumb", title: "View #{project.name}" do %>
                <% if project.project_logo.attached? %>
                    <%= image_tag project.project_logo %>
                <% else %>
                    <%= project.name %>
                <% end %>
            <% end %>
            </div>
        
            <% if current_user %>
                <div class="controls">
                    <% if controller_path !="home" %>
                        <% if project.hidden %>
                        <i class="fal fa-eye-slash fa-xs" aria-hidden="true" title="Hidden"></i>
                        <% else %>
                            <i class="fal fa-eye fa-xs" aria-hidden="true" title="Visible"></i>
                        <% end %>
                    <% end %>
                    <%= link_to edit_project_path(project), title: "Edit" do %>
                        <i class="fal fa-pen fa-xs" aria-hidden="true"></i>
                    <% end %>
                    <% if is_admin(current_user) %>
                        <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete" do %>
                            <i class="fal fa-trash-alt fa-xs red"></i>
                        <% end %>
                    <% else %>
                        <a onClick="alert('You are not an admin!')" title="Delete"><i class="fal fa-trash-alt fa-xs red"></i></a>
                    <% end %>
                </div>
            <% end %>
        
        <div id="modal-<%= project.order_id %>" hidden>
            <div class="modal-popup">
                <div class="row img">
                    <% if project.cover_image.attached? %>
                        <%= image_tag project.cover_image %>
                    <% end %>
                    <% if project.logo.attached? %>
                        <%= image_tag project.logo, class: "logo", title: "Logo" %>
                    <% end %>
                    <% if project.main_tech.attached? %>
                        <%= image_tag project.main_tech, class: "main-tech", title: "Main technology" %>
                    <% end %>
                </div>
                <div class="row"><h5><%= project.name %></h5></div>
                
                <div class="row">
                    <ul class="tag">
                        <% for tag in project.tags.order("name ASC") %>
                            <li><%= tag.name %></li>
                        <% end %>
                    </ul>
                </div>
                <div class="row desc">
                    <%= project.description %>
                </div>
                <div class="links">
                    <div class="row">
                        <div class="column large-6">
                            <%= link_to 'Go to the website', project.url, target: :_blank, title: "View Live" %>
                        </div>
                        <div class="column large-6">
                            <% if project.github_url? %>
                                <%= link_to project.github_url, target: :_blank, title: "View on GitHub" do %>
                                    <i class="fab fa-github"></i>
                                <% end %>
                            <% end %>
                            <% if project.docker_url? %>
                                <%= link_to project.docker_url, target: :_blank, title: "View on DockerHub " do %>
                                    <i class="fab fa-docker"></i>
                                <% end %>
                            <% end %>
                        </div>

                    </div>
                </div>
                
                
            </div>
        </div></div>
    <% end %>
    
</div>
<div class="row h-add-half-top">
    <div class="align-center">
        <% if current_user %>
            <%= link_to new_project_path, title: "Add new" do %><i class="fal fa-plus-circle fa-lg" ></i><% end %>
        <% end %>
    </div>
</div>

alexrogna/app/views/projects/_tag_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "h-full-width" %>
        <%= link_to_remove_association "Remove Tag", f %>
    </div>
</div>

alexrogna/app/views/projects/edit.html.erb
<section class="projects_form">
  <div class="row">
    <div class="column large-12 tab-8 mob-12 align-center">
      <h1>Editing Project</h1>

      <%= render 'form', project: @project %>

      <div class="row">
        <div class="column">
          <%= link_to 'Back', root_path + "#portfolio" %>
        </div>
        <div class="column">
          <% if current_user %>
            <%= link_to 'New Project', new_project_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="portfolio" class="s-portfolio target-section">
  <%= render 'projects/index', projects: @projects %>
</section>

alexrogna/app/views/projects/new.html.erb
<section class="projects_form">
  <div class="row">
    <div class="column large-12 tab-8 mob-12 align-center">
      <h1>New Project</h1>

      <%= render 'form', project: @project %>

      <%= link_to 'Back', root_path + "#portfolio" %>
    </div>
  </div>
</section>
<section id="portfolio" class="s-portfolio target-section">
  <%= render 'projects/index', projects: @projects %>
</section>

alexrogna/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @project.url %>
</p>

<p>
  <strong>Github url:</strong>
  <%= @project.github_url %>
</p>

<p>
  <strong>Docker url:</strong>
  <%= @project.docker_url %>
</p>
<h3>Tags</h3>
<ul>
    <% for @tag in @project.tags %>
        <li><%= @tag.name %></li>
    <% end %>
</ul>
<p>
<% if @project.cover_image.attached? %>
      <%= image_tag @project.cover_image.variant(resize_to_limit: local_assigns.fetch(:cover_image_options, [200, 200])) %>
  <% end %>
</p>
<p>
  <% if @project.logo.attached? %>
      <%= image_tag @project.logo.variant(resize_to_limit: local_assigns.fetch(:logo_options, [200, 200])) %>
  <% end %>
</p> 
<p>
  <% if @project.main_tech.attached? %>
      <%= image_tag @project.main_tech.variant(resize_to_limit: local_assigns.fetch(:main_tech_options, [200, 200])) %>
  <% end %>
</p>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', root_path %>