alexrogna/config/routes.rb
Rails.application.routes.draw do
  resources :personal_skills
  resources :contact_forms
  resources :educations
  resources :teches
  resources :works
  resources :language_skills
  resources :skills do
    resources :books
    resources :hacker_ranks
    resources :free_code_camps
    resources :linkedins
  end
  resources :books
  resources :hacker_ranks
  resources :free_code_camps
  resources :linkedins
  resources :tags
  resources :projects
  resources :social_icons
  namespace :settings do
    resource :user, only: [:show, :update] do
      member do
        post :notify_friend
      end
    end
  end
  devise_for :users, controllers: { sessions: "sessions" }
  get :cv, to: "cv#pdf"
  root "home#index"
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

alexrogna/app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :books
  has_and_belongs_to_many :hacker_ranks
  has_and_belongs_to_many :free_code_camps
  has_and_belongs_to_many :linkedins
  has_and_belongs_to_many :teches
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :books, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :hacker_ranks, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :free_code_camps, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :linkedins, reject_if: :all_blank, allow_destroy: true
  has_one_attached :logo
end

alexrogna/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  # GET /skills or /skills.json
  def _index
    
    @book = Book.all
    @linkedin = Linkedin.all
    @free_code_camp = FreeCodeCamp.all
    @hacker_rank = HackerRank.all

    book = params[:book]
    linkedin = params[:linkedin]
    free_code_camp = params[:free_code_camp]
    hacker_rank = params[:hacker_rank]

    if !book.nil?
      @skills = Skill.joins(:books).where(books: {id: book})
    elsif !linkedin.nil?
      @skills = Skill.joins(:linkedins).where(linkedins: {id: linkedin})
    elsif !free_code_camp.nil?
      @skills = Skill.joins(:free_code_camps).where(free_code_camps: {id: free_code_camp})
    elsif !hacker_rank.nil?
      @skills = Skill.joins(:hacker_ranks).where(hacker_ranks: {id: hacker_rank})
    else
      @skills = Skill.all
    end
  end

  # GET /skills/1 or /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
    @skills = Skill.all.order("order_id ASC")
  end

  # GET /skills/1/edit
  def edit
    @skills = Skill.all.order("order_id ASC")
  end

  # POST /skills or /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to root_path + "#skills", notice: "Skill was successfully created." }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1 or /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to root_path + "#skills", notice: "Skill was successfully updated." }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1 or /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to root_path + "#skills", notice: "Skill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skill_params
      params.require(:skill).permit(:name, :logo, :order_id, book_ids: [], books_attributes:[:title, :subtitle, :author, :publisher, :dop, :resources_link, :github_link, :cover, :_destroy], linkedin_ids: [], linkedins_attributes:[:badge_name, :badge, :_destroy], free_code_camp_ids: [], free_code_camps_attributes:[:cerificate_name, :url, :certificate, :_destroy], hacker_rank_ids: [], hacker_ranks_attributes:[:cerificate_name, :is_badge, :url, :badgeorcertificate, :_destroy] )
    end
end

alexrogna/app/helpers/skills_helper.rb
module SkillsHelper
end

alexrogna/app/views/skills/_book_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: "h-full-width" %>  
    </div>
    <div class="field">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "h-full-width" %>  
    </div>
    <div class="field">
        <%= f.label :author %>
        <%= f.text_field :author, class: "h-full-width" %>  
    </div>
    <div class="field">
        <%= f.label :publisher %>
        <%= f.text_field :publisher, class: "h-full-width" %>  
    </div>
    <div class="field">
        <%= f.label "Date of publication", class: "h-full-width" %>
        <%= f.date_field :dop %>  
    </div>
    <div class="field">
        <%= f.label :resources_link %>
        <%= f.text_field :resources_link, class: "h-full-width" %>  
    </div>
    <div class="field">
        <%= f.label :github_link %>
        <%= f.text_field :github_link, class: "h-full-width" %>  
    </div>
    <div class="field">
        <%= f.label :cover, class: "h-full-width" %>
        <%= f.file_field :cover %>
    </div>
    <%= link_to_remove_association "Remove Book", f %>
</div>

alexrogna/app/views/skills/_form.html.erb
<%= form_with(model: skill) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% skill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "h-full-width" %>
  </div>
  <div class="field">
    <%= form.label :logo %>
    <% if skill.logo.attached? %>
        <%= image_tag skill.logo.variant(resize_to_limit: local_assigns.fetch(:logo_options, [200, 200])) %>
    <% end %>
    <%= form.file_field :logo %>
    <hr>
  </div>
  <div class="field">
    <%= form.label :order_id %>
    <%= form.number_field :order_id, class: "h-full-width" %>
  </div>
  <div class="field">
    <h3>Add Linkedin</h3>
    <%= form.collection_check_boxes(:linkedin_ids, Linkedin.all, :id, :badge_name) do |b| %>
      <% b.label {b.check_box + b.text } %>
    <% end %>
    <div class="links">
        <%= link_to_add_association "Add Linkedin", form, :linkedins %>
    </div>
  </div>
  <%= link_to "View Linkedins", linkedins_path %>
  <hr>
  <div class="field">
    <h3>Add FreeCodeCamp</h3>
    <%= form.collection_check_boxes(:free_code_camp_ids, FreeCodeCamp.all, :id, :cerificate_name) do |b| %>
      <% b.label {b.check_box + b.text } %>
    <% end %>
    <div class="links">
        <%= link_to_add_association "Add FreeCodeCamp", form, :free_code_camps %>
    </div>
  </div>
  <%= link_to "View FreeCodeCamp", free_code_camps_path %>
  <hr>
  <div class="field">
    <h3>Add HackerRank</h3>
    <%= form.collection_check_boxes(:hacker_rank_ids, HackerRank.all, :id, :cerificate_name) do |b| %>
      <% b.label {b.check_box + b.text } %>
    <% end %>
    <div class="links">
        <%= link_to_add_association "Add HackerRank", form, :hacker_ranks %>
    </div>
  </div>
  <%= link_to "View HackerRank", hacker_ranks_path %>
  <hr>
  <div class="field">
    <h3>Add Book</h3>
    <%= form.collection_check_boxes(:book_ids, Book.all, :id, :title) do |b| %>
      <% b.label {b.check_box + b.text} %>
    <% end %>
    <div class="links">
        <%= link_to_add_association "Add Book", form, :books %>
    </div>
  </div>
  <%= link_to "View Books", books_path %>
  <hr>
  <div class="actions">
    <%= form.submit class: "btn btn--submit h-full-width", disabled: !is_admin(current_user) %>
  </div>
<% end %>

alexrogna/app/views/skills/_free_code_camp_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :cerificate_name %>
        <%= f.text_field :cerificate_name, class: "h-full-width" %>
    </div>
    <div class="field">
        <%= f.label :url %>
        <%= f.text_field :url, class: "h-full-width" %>
    </div>
    <div class="field">
        <%= f.label :certificate, class: "h-full-width" %>
        <%= f.file_field :certificate %>
    </div>
     <%= link_to_remove_association "Remove Free Code Camp", f %>
</div>

alexrogna/app/views/skills/_hacker_rank_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :cerificate_name %>
        <%= f.text_field :cerificate_name, class: "h-full-width" %>
    </div>
    <div class="field">
        <%= f.label :is_badge %>
        <%= f.check_box :is_badge %>
    </div>
    <div class="field">
        <%= f.label :url %>
        <%= f.text_field :url, class: "h-full-width" %>
    </div>
    <div class="field">
        <%= f.label "Badge or certificate (on hackerrank->right click->inspect->copy all svg tag here)", class: "h-full-width" %>
        <%= f.text_area :badgeorcertificate, class: "h-full-width" %>
    </div>
    <%= link_to_remove_association "Remove Hacker Rank", f %>
</div>

alexrogna/app/views/skills/_index.html.erb
<header class="row">
    <div class="column large-12">
        <h3 class="section-header-allcaps">Skills</h3>
    </div>
</header>

<main class="row collapse block-large-1-5 block-medium-1-4 block-tab-1-2"><% @badge=true %>
    <% @skills.each do |skill| %>
        <div class="column">
            <div class="skill">
                <div class="row">
                    <div class="thumb">
                        <% if skill.logo.attached? %>
                            <%= image_tag skill.logo, title: skill.name %>
                        <% end %>
                    </div>
                </div>
                <div class="row collapse">
                    <div class="column skill-item">  
                        <% if skill.books.count()>0 %>              
                            <%= link_to "#modal-#{skill.id}-books", title: "View what books I've read" do %>
                                <i class="fas fa-book"></i>
                            <% end %>   
                        <% else %> 
                            <i class="fas fa-book deactivated"></i>
                        <% end %>
                    </div>  
                    <div class="column collapse skill-item">
                        <% if skill.linkedins.count()>0 %>
                            <%= link_to "#modal-#{skill.id}-linkedins", title: "View what LinkedIn badges I have" do %>
                                <i class="fab fa-linkedin-in"></i>
                            <% end %> 
                            <% else %>    
                                <i class="fab fa-linkedin-in deactivated"></i>      
                        <% end %>
                    </div>  
                    <div class="column collapse skill-item">
                        <% if skill.hacker_ranks.count()>0 %>
                            <%= link_to "#modal-#{skill.id}-hacker_ranks", title: "View what HackerRank badges and certificates I have" do %>
                                <i class="fab fa-hackerrank"></i>
                            <% end %> 
                            <% else %>      
                                <i class="fab fa-hackerrank deactivated"></i>    
                        <% end %>
                    </div>  
                    <div class="column collapse skill-item">
                        <% if skill.free_code_camps.count()>0 %>
                            <%= link_to "#modal-#{skill.id}-free_code_camps", title: "View what certificates I have" do %>
                                <i class="far fa-file-certificate"></i>
                            <% end %>  
                            <% else %>         
                                <i class="far fa-file-certificate deactivated"></i>
                        <% end %>
                    </div> 
                </div>
            </div> 
            <div id="modal-<%= skill.id %>-books" hidden>
                <div class="modal-popup-skills-b">
                    <div class="row"><h3 class="align-center">Books I've read</h3></div>
                    <%= render skill.books.with_attached_cover.order("dop DESC") %>
                </div>
            </div>
            <div id="modal-<%= skill.id %>-linkedins" hidden>
                <div class="row modal-title-skills-li"><h3 class="align-center">Badges on Linkedin</h3></div>
                <div class="row collapse block-large-1-2 block-500-stack modal-popup-skills-li">
                    <%= render skill.linkedins.with_attached_badge %>
                </div>
            </div>
            <div id="modal-<%= skill.id %>-hacker_ranks" hidden>
                <% if skill.hacker_ranks.count{ |hacker_rank| hacker_rank.is_badge? } > 0 %>
                    <div class="row modal-popup-skills-hr">
                        <div class="column large-12"><h3><i class="far fa-id-badge"></i> Badges on HackerRank</h3></div>
                <% else %>
                    <div>
                <% end %>
                    <% @badge=true %>
                    <%= render skill.hacker_ranks.order("is_badge DESC") %>
                </div>
                
            </div>
            <div id="modal-<%= skill.id %>-free_code_camps" hidden>
            <div class="row modal-title-skills-fcc"><h3 class="align-center">Certificates</h3></div>
                <div class="row collapse block-large-1-2 block-500-stack modal-popup-skills-fcc">
                    <%= render skill.free_code_camps.with_attached_certificate %>
                </div>
            </div>
            <% if current_user %>
                <div class="controls">
                    <%= link_to edit_skill_path(skill), title: "Edit" do %>
                        <i class="fal fa-pen fa-xs" aria-hidden="true"></i>
                    <% end %>
                    <% if is_admin(current_user) %>
                        <%= link_to skill, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete" do %>
                            <i class="fal fa-trash-alt fa-xs red"></i>
                        <% end %>
                    <% else %>
                        <a onClick="alert('You are not an admin!')" title="Delete"><i class="fal fa-trash-alt fa-xs red"></i></a>
                    <% end %>
                </div>
            <% end %>
        </div>
    <% end %>
    <div class="row h-add-half-top">
        <% if current_user %>
            <%= link_to new_skill_path, title: "Add new" do %><i class="fal fa-plus-circle fa-lg" ></i><% end %>
        <% end %>
    </div>
</main>

<footer class="row"></footer>

alexrogna/app/views/skills/_linkedin_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :badge_name %>
        <%= f.text_field :badge_name, class: "h-full-width" %>   
    </div>
    <div class="field">
        <%= f.label :badge, class: "h-full-width" %>
        <%= f.file_field :badge %>
    </div>
    <%= link_to_remove_association "Remove Linkedin", f %>
</div>

alexrogna/app/views/skills/edit.html.erb
<section class="skills_form">
  <div class="row">
    <div class="column large-12 tab-8 mob-12 align-center">
      <h1>Editing Skill</h1>

      <%= render 'form', skill: @skill %>

      <div class="row">
        <div class="column">
          <%= link_to 'Back', root_path + "#skills" %>
        </div>
        <div class="column">
          <% if current_user %>
            <%= link_to 'New Skill', new_skill_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="skills" class="s-skills target-section">
  <%= render 'skills/index' %>
</section>

alexrogna/app/views/skills/new.html.erb
<section class="skills_form">
  <div class="row">
    <div class="column large-12 tab-8 mob-12 align-center">
      <h1>New Skill</h1>

      <%= render 'form', skill: @skill %>

      <%= link_to 'Back', root_path + "#skills" %>
    </div>
  </div>
</section>
<section id="skills" class="s-skills target-section">
  <%= render 'skills/index' %>
</section>

alexrogna/app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Books</strong>

</p>
<% for @book in @skill.books %>
    <li><%= @book.title %></li>
    <li><%= @book.publisher %></li>
    <li><%= @book.dop %></li>
    <hr>
<% end %>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>