alexrogna/config/routes.rb
Rails.application.routes.draw do
  resources :personal_skills
  resources :contact_forms
  resources :educations
  resources :teches
  resources :works
  resources :language_skills
  resources :skills do
    resources :books
    resources :hacker_ranks
    resources :free_code_camps
    resources :linkedins
  end
  resources :books
  resources :hacker_ranks
  resources :free_code_camps
  resources :linkedins
  resources :tags
  resources :projects
  resources :social_icons
  namespace :settings do
    resource :user, only: [:show, :update] do
      member do
        post :notify_friend
      end
    end
  end
  devise_for :users, controllers: { sessions: "sessions" }
  get :cv, to: "cv#pdf"
  root "home#index"
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

alexrogna/app/models/education.rb
class Education < ApplicationRecord
  has_and_belongs_to_many :teches
  accepts_nested_attributes_for :teches, reject_if: :all_blank, allow_destroy: true
  has_rich_text :courses
end

alexrogna/app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  # GET /educations or /educations.json
  def index
    
    @teches = Tech.all
    tech = params[:tech]
    if !tech.nil?
      @educations = Education.joins(:teches).where(teches: {id: tech})
    else
      @educations = Education.all
    end
  end

  # GET /educations/1 or /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
    @educations = Education.all.order('start_date DESC')
  end

  # GET /educations/1/edit
  def edit
    @educations = Education.all.order('start_date DESC')
  end

  # POST /educations or /educations.json
  def create
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to root_path + "#education", notice: "Education was successfully created." }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1 or /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to root_path + "#education", notice: "Education was successfully updated." }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1 or /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to root_path + "#education", notice: "Education was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def education_params
      params.require(:education).permit(:school, :location, :start_date, :end_date, :specialization, :courses, :show_on_cv, :present, tech_ids: [], teches_attributes:[:name, :logo, :_destroy])
    end
end

alexrogna/app/helpers/educations_helper.rb
module EducationsHelper
end

alexrogna/app/views/educations/_form.html.erb
<%= form_with(model: education) do |form| %>
  <% if education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
        <% education.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :school %>
    <%= form.text_field :school, class: "h-full-width", readonly: !is_admin(current_user) %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class: "h-full-width" %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, start_year: 2000, end_year: Date.today.year %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, start_year: 2000, end_year: Date.today.year + 1 %>
  </div>
  <div class="field">
    <%= form.label :present %>
    <%= form.check_box :present %>
  </div>
  <div class="field">
    <%= form.label :specialization %>
    <%= form.text_area :specialization, class: "h-full-width" %>
  </div>
  <div class="field">
    <%= form.label :courses %>
    <%= form.rich_text_area :courses, class: "h-full-width" %>
  </div>
  <div class="field">
    <%= form.label :show_on_cv %>
    <%= form.check_box :show_on_cv %>
  </div>
  <h3>Add Techs</h3>
  <%= form.collection_check_boxes(:tech_ids, Tech.all.order('name ASC'), :id, :name) do |b| %>
    <% b.label {b.check_box + b.text } %>
  <% end %>
  <div class="links">
      <%= link_to_add_association "Add Tech", form, :teches %>
  </div>
  <%= link_to "View Techs", teches_path %>

  <div class="actions">
    <%= form.submit class: "btn btn--submit h-full-width", disabled: !is_admin(current_user)  %>
  </div>
<% end %>

alexrogna/app/views/educations/_index.html.erb
<header class="row">
    <div class="column large-12">
        <h3 class="section-header-allcaps">Education</h3>
    </div>
</header>
<main class="row">
    <% @educations.each do |education| %>
      <div class="education-place large-12">
        <div class="description">
          <h4 class="h-remove-top"><%= education.school %></h4>
          <% if current_user %>
            <div class="controls">
              <%= link_to edit_education_path(education), title: "Edit" do %>
                <i class="fal fa-pen" aria-hidden="true"></i>
              <% end %>
              <% if is_admin(current_user) %>
                <%= link_to education, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete" do %>
                  <i class="fal fa-trash-alt red"></i>
                <% end %>
              <% else %>
                <a onClick="alert('You are not an admin!')" title="Delete"><i class="fal fa-trash-alt red"></i></a>
              <% end %>
            </div>
          <% end %>
          <p class="header-meta">
              <span><%= education.location %></span> 
              <span class="header-date">
                  <%= verbose_date(education.start_date) %> - <%= education.present ? "Present" : verbose_date(education.end_date) %>
              </span>
          </p>
          <p>
            <%= education.specialization %>
          </p>
          <div>
            <%= education.courses %>
          </div>
        </div>
        <div class="row collapse block-large-1-12 block-medium-1-8 block-tab-1-6 block-mob-1-4">
          <% for tech in education.teches.with_attached_logo.order('order_id ASC') %>
            <div class="column">
              <div class="techs tech-<%= tech.id %>" data-tech-class="<%= tech.id %>">
                <% if tech.logo.attached? %>
                  <div class="thumb">
                    <%= image_tag tech.logo,title: "Click to highlight where I've used #{tech.name} in work and education" %>
                  </div>
                <% end %>
              </div> 
              <% if current_user %>
                  <div class="controls align-center">
                    <%= link_to edit_tech_path(tech), title: "Edit" do %>
                      <i class="fal fa-pen" aria-hidden="true"></i>
                  <% end %>
                  <% if is_admin(current_user) %>
                    <%= link_to tech, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete" do %>
                      <i class="fal fa-trash-alt red"></i>
                    <% end %>
                  <% else %>
                    <a onClick="alert('You are not an admin!')" title="Delete"><i class="fal fa-trash-alt red"></i></a>
                  <% end %>
                  </div>
                <% end %> 
            </div>  
          <% end %>
        </div> 
      </div> 
    <% end %>   
    <div class="row">
      <div class="align-center">
        <% if current_user %>
            <%= link_to new_education_path, title: "Add new" do %><i class="fal fa-plus-circle fa-lg" ></i><% end %>
        <% end %>
      </div>
    </div>
</main>

alexrogna/app/views/educations/_tech_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "h-full-width" %>
        <%= f.label :logo %>
        <%= f.file_field :logo, class: "h-full-width" %>
        <%= link_to_remove_association "Remove Tech", f %>
    </div>
</div>

alexrogna/app/views/educations/edit.html.erb
<section class="education_form">
  <div class="row">
    <div class="column large-12 tab-8 mob-12 align-center">
      <h1>Editing Education</h1>

      <%= render 'form', education: @education %>

      <div class="row">
        <div class="column">
          <%= link_to 'Back', root_path + "#education" %>
        </div>
        <div class="column">
        <% if current_user %>
          <%= link_to 'New Education Place', new_education_path %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="education" class="s-education target-section">
  <%= render 'educations/index' %>
</section>

alexrogna/app/views/educations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Educations</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Location</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Specialization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.school %></td>
        <td><%= education.location %></td>
        <td><%= education.start_date %></td>
        <td><%= education.end_date %></td>
        <td><%= education.specialization %></td>
        <td><%= link_to 'Show', education %></td>
        <td><%= link_to 'Edit', edit_education_path(education) %></td>
        <td><%= link_to 'Destroy', education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education', new_education_path %>

alexrogna/app/views/educations/new.html.erb
<section class="education_form">
  <div class="row">
    <div class="column large-12 tab-8 mob-12 align-center">
      <h1>New Education</h1>

      <%= render 'form', education: @education %>

      <%= link_to 'Back', root_path + "#education" %>
    </div>
  </div>
</section>
<section id="education" class="s-education target-section">
  <%= render 'educations/index' %>
</section>

alexrogna/app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @education.school %>
</p>

<p>
  <strong>Location:</strong>
  <%= @education.location %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @education.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @education.end_date %>
</p>

<p>
  <strong>Specialization:</strong>
  <%= @education.specialization %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>