alexrogna/config/routes.rb
Rails.application.routes.draw do
  resources :personal_skills
  resources :contact_forms
  resources :educations
  resources :teches
  resources :works
  resources :language_skills
  resources :skills do
    resources :books
    resources :hacker_ranks
    resources :free_code_camps
    resources :linkedins
  end
  resources :books
  resources :hacker_ranks
  resources :free_code_camps
  resources :linkedins
  resources :tags
  resources :projects
  resources :social_icons
  namespace :settings do
    resource :user, only: [:show, :update] do
      member do
        post :notify_friend
      end
    end
  end
  devise_for :users, controllers: { sessions: "sessions" }
  get :cv, to: "cv#pdf"
  root "home#index"
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

alexrogna/app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :skills
  has_one_attached :cover
end

alexrogna/app/models/contact_form.rb
class ContactForm < ApplicationRecord
  validates :name, :email, :message, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

alexrogna/app/models/education.rb
class Education < ApplicationRecord
  has_and_belongs_to_many :teches
  accepts_nested_attributes_for :teches, reject_if: :all_blank, allow_destroy: true
  has_rich_text :courses
end

alexrogna/app/models/email_a_friend.rb
class EmailAFriend
  include ActiveModel::Model
  
  attr_accessor :name, :email, :yemail

  validates :name, :email, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  
end

alexrogna/app/models/free_code_camp.rb
class FreeCodeCamp < ApplicationRecord
  has_and_belongs_to_many :skills
  has_one_attached :certificate
end

alexrogna/app/models/hacker_rank.rb
class HackerRank < ApplicationRecord
  has_and_belongs_to_many :skills
end

alexrogna/app/models/language_skill.rb
class LanguageSkill < ApplicationRecord
end

alexrogna/app/models/linkedin.rb
class Linkedin < ApplicationRecord
  has_and_belongs_to_many :skills
  has_one_attached :badge
end

alexrogna/app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true
  has_one_attached :cover_image
  has_one_attached :logo
  has_one_attached :main_tech
  has_one_attached :project_logo
  has_rich_text :description
end

alexrogna/app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :books
  has_and_belongs_to_many :hacker_ranks
  has_and_belongs_to_many :free_code_camps
  has_and_belongs_to_many :linkedins
  has_and_belongs_to_many :teches
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :books, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :hacker_ranks, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :free_code_camps, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :linkedins, reject_if: :all_blank, allow_destroy: true
  has_one_attached :logo
end

alexrogna/app/models/social_icon.rb
class SocialIcon < ApplicationRecord
end

alexrogna/app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :skills
  validates :name, uniqueness: true
end

alexrogna/app/models/tech.rb
class Tech < ApplicationRecord
  has_and_belongs_to_many :works
  has_and_belongs_to_many :educations
  has_and_belongs_to_many :skills
  validates :name, uniqueness: true
  has_one_attached :logo
end

alexrogna/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_one_attached :cover_image
  has_one_attached :profile_image
  has_one_attached :cv
  has_rich_text :long_description_wysiwyg
  has_rich_text :extra_description_for_pdf
end

alexrogna/app/models/work.rb
class Work < ApplicationRecord
  has_and_belongs_to_many :teches
  accepts_nested_attributes_for :teches, reject_if: :all_blank, allow_destroy: true
  has_rich_text :key_responsibilities
end

alexrogna/app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  # GET /works or /works.json
  def index
    @teches = Tech.all
    tech = params[:tech]
    if !tech.nil?
      @works = Work.joins(:teches).where(teches: {id: tech})
    else
      @works = Work.all
    end
  end

  # GET /works/1 or /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
    @works = Work.all.order('start_date DESC')
  end

  # GET /works/1/edit
  def edit
    @works = Work.all.order('start_date DESC')
  end

  # POST /works or /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to root_path + "#work", notice: "Work was successfully created." }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1 or /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to root_path + "#work", notice: "Work was successfully updated." }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1 or /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to root_path + "#work", notice: "Work was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_params
      params.require(:work).permit(:company, :position, :start_date, :end_date, :present, :key_responsibilities, :description, tech_ids: [], teches_attributes:[:name, :logo, :_destroy])
    end
end

alexrogna/app/helpers/books_helper.rb
module BooksHelper
end

alexrogna/app/helpers/cv_helper.rb
module CvHelper
  def links(link)
    link.gsub("https://", "")
  end
end

alexrogna/app/helpers/home_helper.rb
module HomeHelper
  def procent(skill)
    # total projects, work places and education places
    total = @projects.count + @works.count + @educations.count
    #start from 0
    found_in_projects=found_in_work_places=found_in_education_places=0 
    # how many times is found the skill by name tag in projects
    @projects.each do |project| 
      found_in_projects += project.tags.count{ |tag| tag.name.downcase==skill.name.downcase||(tag.skills.count{|s| s.name.downcase==skill.name.downcase}>0) } 
    end 
    #how many times is found the skill by name tech in work places
    @works.each do |work| 
      found_in_work_places += work.teches.count{ |tech| tech.name.downcase==skill.name.downcase||(tech.skills.count{|s| s.name.downcase==skill.name.downcase}>0) }  
    end 
    #how many times is found the skill by name tech in education places
    @educations.each do |education| 
      found_in_education_places += education.teches.count{ |tech| tech.name.downcase==skill.name.downcase||(tech.skills.count{|s| s.name.downcase==skill.name.downcase}>0) } 
    end 
    # how many times is found the skill in projects, work places and half of the education places, books, linkedin badges, hacker rank certificate and badges, free code camp certificate (this is count as half because is more important to use the skill in real projects/work than to read about it) 
    found_skill = found_in_projects + found_in_work_places + (found_in_education_places + skill.books.count + skill.linkedins.count + skill.hacker_ranks.count + skill.free_code_camps.count)/2
    # final calculation: how many time is found the skill from total 
    (found_skill * 100 / total).to_i
  end 
end

alexrogna/app/helpers/skills_helper.rb
module SkillsHelper
end

alexrogna/app/helpers/tags_helper.rb
module TagsHelper
end

alexrogna/app/helpers/teches_helper.rb
module TechesHelper
end

alexrogna/app/helpers/works_helper.rb
module WorksHelper
end

alexrogna/app/views/works/_form.html.erb
<%= form_with(model: work) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
        <% work.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, class: "h-full-width" %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position, class: "h-full-width" %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, start_year: 2000, end_year: Date.today.year %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, start_year: 2000, end_year: Date.today.year %>
  </div>

  <div class="field">
    <%= form.label :present %>
    <%= form.check_box :present %>
  </div>
  <div class="field">
    <%= form.label :key_responsibilities %>
    <%= form.rich_text_area :key_responsibilities, class: "h-full-width" %>
  </div>
  <div class="field">
    <%= form.label "Is description" %>
    <%= form.check_box :description %>
  </div>
  <h3>Add Techs</h3>
  <%= form.collection_check_boxes(:tech_ids, Tech.all.order('name ASC'), :id, :name) do |b| %>
    <% b.label {b.check_box + b.text } %>
  <% end %>
  <div class="links">
      <%= link_to_add_association "Add Tech", form, :teches %>
  </div>
  <%= link_to "View Techs", teches_path %>

  <div class="actions">
    <%= form.submit class: "btn btn--submit h-full-width", disabled: !is_admin(current_user) %>
  </div>
<% end %>

alexrogna/app/views/works/_index.html.erb
<header class="row">
    <div class="column large-12">
        <h3 class="section-header-allcaps">Work Experience</h3>
    </div>
</header>
<main class="row">
    <% @works.each do |work| %>
      <div class="work-place large-12">
        <div class="description">
            <h4 class="h-remove-top"><%= work.company %>
            </h4>
            <% if current_user %>
                <div class="controls">
                    <%= link_to edit_work_path(work), title: "Edit" do %>
                        <i class="fal fa-pen" aria-hidden="true"></i>
                    <% end %>
                    <% if is_admin(current_user) %>
                        <%= link_to work, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete" do %>
                            <i class="fal fa-trash-alt red"></i>
                        <% end %>
                    <% else %>
                        <a onClick="alert('You are not an admin!')" title="Delete"><i class="fal fa-trash-alt red"></i></a>
                    <% end %>
                </div>
            <% end %>
            <p class="header-meta">
                <span><%= work.position %></span> 
                <span class="header-date">
                    <%= verbose_date(work.start_date) %> - <%= work.present ? "Present" : verbose_date(work.end_date)%>
                </span>
            </p>
            <div>
                <% if work.description? %>
                    Description
                <% else %>
                    Key Responsibilities 
                <% end %>
                <br>
                <%= work.key_responsibilities %>
            </div>
            Tools <br>
        </div>
        <div class="row collapse block-large-1-12 block-medium-1-8 block-tab-1-6 block-mob-1-4">
        
            <% for tech in work.teches.with_attached_logo.order('order_id ASC') %>
                <div class="column">
                    <div class="techs tech-<%= tech.id %>" data-tech-class="<%= tech.id %>">
                        <% if tech.logo.attached? %>
                            <div class="thumb">
                                <%= image_tag tech.logo,title: "Click to highlight where I've used #{tech.name} in work and education" %>
                            </div>
                        <% end %>
                    </div>
                    <% if current_user %>
                        <div class="controls align-center">
                            <%= link_to edit_tech_path(tech), title: "Edit" do %>
                                <i class="fal fa-pen" aria-hidden="true"></i>
                            <% end %>
                            <% if is_admin(current_user) %>
                                <%= link_to tech, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete" do %>
                                    <i class="fal fa-trash-alt red"></i>
                                <% end %>
                            <% else %>
                                <a onClick="alert('You are not an admin!')" title="Delete"><i class="fal fa-trash-alt red"></i></a>
                            <% end %>
                        </div>
                    <% end %>
                </div> 
            <% end %>
        </div>
        
      </div> 
    <% end %> 
    <div class="row">
        <div class="align-center">
            <% if current_user %>
                <%= link_to new_work_path, title: "Add new" do %><i class="fal fa-plus-circle fa-lg" ></i><% end %>
            <% end %>
        </div>
    </div>
</main>
<footer class="row"></footer>

alexrogna/app/views/works/_tech_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "h-full-width" %>
        <%= f.label :logo, class: "h-full-width" %>
        <%= f.file_field :logo, class: "h-full-width" %>
        <%= link_to_remove_association "Remove Tech", f %>
    </div>
</div>

alexrogna/app/views/works/edit.html.erb
<section class="works_form">
  <div class="row">
    <div class="column large-12 tab-8 mob-12 align-center">
      <h1>Editing Work</h1>

      <%= render 'form', work: @work %>

      <div class="row">
        <div class="column">
          <%= link_to 'Back', root_path + "#work" %>
        </div>
        <div class="column">
        <% if current_user %>
          <%= link_to 'New Work Place', new_work_path %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="work" class="s-work target-section">
  <%= render 'works/index' %>
</section>

alexrogna/app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Position</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Present</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.company %></td>
        <td><%= work.position %></td>
        <td><%= work.start_date %></td>
        <td><%= work.end_date %></td>
        <td><%= work.present %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

alexrogna/app/views/works/new.html.erb
<section class="works_form">
  <div class="row">
    <div class="column large-12 tab-8 mob-12 align-center">
      <h1>New Work</h1>

      <%= render 'form', work: @work %>

      <%= link_to 'Back', root_path + "#work" %>
    </div>
  </div>
</section>
<section id="work" class="s-work target-section">
  <%= render 'works/index' %>
</section>

alexrogna/app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @work.company %>
</p>

<p>
  <strong>Position:</strong>
  <%= @work.position %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @work.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @work.end_date %>
</p>

<p>
  <strong>Present:</strong>
  <%= @work.present %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>